
version: '3.5'
services:
   web-server:
      image: nginx:1.26.1
      container_name: nginx
      volumes: 
        - ./static:/usr/share/nginx/html
      ports:
        - '80:80'
        - '443:443'
      restart: unless-stopped
networks:
  default:
    driver: bridge
    name: webnet

