
version: '3.5'
services:
   wev-server:
      image: nginx:1.26.1
      container_name: mynginx
      volumes: 
        - ./static:/var/www/html
      ports:
        - '80:80'
        - '443:443'
      restart: unless-stopped
networks:
  default:
    driver: bridge
    name: webnet

